#!/bin/bash
case $1 in
    pack-files)
        add_to_archive "$CONFIG_DIR" "config"
        add_to_archive "$SCRIPTS_DIR" "scripts"
        add_to_archive "$BOOTSTRAP_DIR" "bootstrap"
        ;;
        
    install)
        create_dir $CONFIG_DIR
        create_dir $SCRIPTS_DIR
        create_dir $BOOTSTRAP_DIR
        
        copy_data config $MINI2440_ROOT
        copy_data scripts $MINI2440_ROOT
        copy_data bootstrap $MINI2440_ROOT
        
        create_link buildroot/output/host $MINI2440_ROOT/host
        create_link buildroot/output/images $MINI2440_ROOT/images
        create_link buildroot/output/target $MINI2440_ROOT/target
        ;;
esac
