#!/bin/bash
QEMU_SRC_DIR=$MINI2440_ROOT/qemu
QEMU_REPO=git://repo.or.cz/qemu/mini2440.git

case $1 in
    pack-files)
        git_patch_to_archive $QEMU_SRC_DIR qemu-custom.patch
        ;;
        
    install)
        git clone $QEMU_REPO $QEMU_SRC_DIR
        cd $QEMU_SRC_DIR
        
        pecho "Applying patch ..."
		patch -p1 -i $INSTALL_DATA/qemu-custom.patch || exit 1
		
        pecho "Configuring qemu ... "
		./configure --target-list=arm-softmmu
		
		pecho "Building qemu ... "
		make -j2 || exit 1
		;;
esac
