#!/bin/bash

BOOTSTRAP_SCRIPTS=$BOOTSTRAP_DIR/scripts
BOOTSTRAP_FUNCTIONS=$BOOTSTRAP_DIR/functions.d
BOOTSTRAP_MODULES=$BOOTSTRAP_DIR/modules.d

#
# Bootstrap parameters
#

OUTPUT=$1
ARCHIVE=test.tar
XARCHIVE=test.tar.bz2


# Canonicalize vars
OUTPUT_FINAL=$(readlink -f $OUTPUT)
OUTPUT=$(readlink -f $OUTPUT.tmp)
ARCHIVE=$(readlink -f $ARCHIVE)

export BOOTSTRAP_DIR
export BOOTSTRAP_SCRIPTS
export BOOTSTRAP_FUNCTIONS
export BOOTSTRAP_MODULES
export ARCHIVE


#
# Bootstrap script creation
#

# Generate the payload
[ -f $ARCHIVE ] && rm $ARCHIVE
echo "Processing data"
$BOOTSTRAP_SCRIPTS/pack
bzip2 $ARCHIVE
echo "done : $XARCHIVE."

# Shebang
echo "" > $OUTPUT

# Generate module functions
echo "Generating modules"
MODULE_LIST=""
for moduleFile in `ls -1 $BOOTSTRAP_MODULES`
do
    moduleName=`echo $moduleFile | sed "s/^[0-9]*//"`
    echo -n "    $moduleName ... "
    
    echo "function module_${moduleName} {" >> $OUTPUT
    tail -n +2 $BOOTSTRAP_MODULES/$moduleFile >> $OUTPUT
    echo -e "}\n\n" >> $OUTPUT
    
    MODULE_LIST="$MODULE_LIST $moduleName"
    echo "ok"
done
echo "done."

# Self-information
echo -n "Generating self-information ..."
echo "BOOTSTRAP_MODULES=\"$MODULE_LIST\"" >> $OUTPUT

git --work-tree $MINI2440_ROOT --git-dir $MINI2440_ROOT/.git/ status 1>/dev/null 2>/dev/null
if [[ $? -ne 0 ]]
then
    BOOTSTRAP_SCRIPT_VERSION="skyposcope-unknown"
    BOOTSTRAP_SCRIPT_BRANCH="custom"
    BOOTSTRAP_SCRIPT_AUTHOR="$(whoami)@$(hostname)"
else
    BOOTSTRAP_SCRIPT_VERSION=`git --git-dir $MINI2440_ROOT/.git describe --tags 2>/dev/null`
    BOOTSTRAP_SCRIPT_AUTHOR="$(git config user.name) ($(git config user.email))"
    
    cBranch=$(git branch | grep "*")
    BOOTSTRAP_SCRIPT_BRANCH=${cBranch/* /}
fi

echo "BOOTSTRAP_SCRIPT_VERSION=\"${BOOTSTRAP_SCRIPT_VERSION}\"" >> $OUTPUT
echo "BOOTSTRAP_SCRIPT_BRANCH=\"${BOOTSTRAP_SCRIPT_BRANCH}\"" >> $OUTPUT
echo "BOOTSTRAP_SCRIPT_AUTHOR=\"${BOOTSTRAP_SCRIPT_AUTHOR}\"" >> $OUTPUT
echo "BOOTSTRAP_SCRIPT_DATE=\"$(LC_ALL=C date)\"" >> $OUTPUT
echo "done."

# Add source scripts
echo "Generating bootstrap functions"
for bootstrapScript in `ls -1 $BOOTSTRAP_FUNCTIONS` 
do
    echo -n "    $bootstrapScript ... "
    
    tail -n +2 $BOOTSTRAP_FUNCTIONS/$bootstrapScript >> $OUTPUT
    
    echo "ok".
done
echo "done."

# Exit the shell script to prevent payload execution
echo "exit 0" >> $OUTPUT

# Payload data to embed
echo -n "Embedding data ... "
echo 'DATA:' >> $OUTPUT
cat $XARCHIVE >> $OUTPUT
echo "done."


# Generate the real script with checksum
echo "#!/bin/bash" > $OUTPUT_FINAL

checksum=$(md5sum $OUTPUT | cut -d" " -f1)
echo "# $checksum" >> $OUTPUT_FINAL
cat $OUTPUT >> $OUTPUT_FINAL

rm $OUTPUT
rm $XARCHIVE
chmod a+x $OUTPUT_FINAL
echo "Bootstrap script is ready : $OUTPUT_FINAL"
