#!/bin/bash

MINI2440_ROOT=$(readlink -f .)
ACTION="complete-bootstrap"
INSTALL_MODULE=""
EXTRACT_LOCATION="."

while [ $# -gt 0 ]
do
    case $1 in
        --root)      MINI2440_ROOT=$2; shift;;
        --install)  
            ACTION="install"; 
            INSTALL_MODULE=$2; 
            shift
            ;;
            
        --extract-data)
            ACTION="extract";
            EXTRACT_LOCATION=$2;
            shift
            ;;
            
        --list-modules|--info)
            ACTION="info"
            ;;
            
        --version)
            ACTION="version"
            ;;
            
        --help)
            ACTION="help"
            ;;
            
        --check|--check-integrity)
            ACTION="check"
            ;;

        --*|-*) echo "Unrecognized option $1"; exit 1;;
        *)      echo "Ignoring extra data '$1'";;
    esac

    shift
done

# Generate hierarchy informations
HOST_DIR=$MINI2440_ROOT/host
TARGET_DIR=$MINI2440_ROOT/target
IMAGES_DIR=$MINI2440_ROOT/images
CONFIG_DIR=$MINI2440_ROOT/config
SCRIPTS_DIR=$MINI2440_ROOT/scripts
BOOTSTRAP_DIR=$MINI2440_ROOT/bootstrap
BUILDROOT_DIR=$MINI2440_ROOT/buildroot
DOWNLOAD_DIR=$MINI2440_ROOT/download

export MINI2440_ROOT
export HOST_DIR
export TARGET_DIR
export IMAGES_DIR
export CONFIG_DIR
export SCRIPTS_DIR
export BOOTSTRAP_DIR
export BUILDROOT_DIR
export DOWNLOAD_DIR

# Check if the install dir exists
if [ ! -d $MINI2440_ROOT ]
then
    echo "Directory $MINI2440_ROOT doesn't exists."
    exit 1
fi

# Extract payload
BOOTSTRAP_DATA=$(readlink -f $MINI2440_ROOT/.bootstrapdata)
export BOOTSTRAP_DATA

case $ACTION in
    complete-bootstrap)
		BEGIN=$(date +%s)
        bootstrap_extract "$0" "$BOOTSTRAP_DATA"
        
        for module in $BOOTSTRAP_MODULES
        do
            pecho "Processing module $module"
            fn="module_${module}"
            $fn install
        done
        
        rm -rf $BOOTSTRAP_DATA
        
		END=$(date +%s)
		TOTALTIME=$(($END-$BEGIN))

		echo "Build time: $TOTALTIME seconds."
        exit 0
        ;;
    
    install)
        bootstrap_extract "$0" "$BOOTSTRAP_DATA"
        fn="module_${INSTALL_MODULE}"
        $fn install
        rm -rf $BOOTSTRAP_DATA
        exit 0
        ;;
        
        
    check)
        this_checksum=$(tail -n +2 $0 | head -1 | cut -d" " -f2)
        calculated_checksum=$(tail -n +3 $0 | md5sum | cut -d" " -f1)
        
        if [[ "$this_checksum" != "$calculated_checksum" ]]
        then
            echo "Checksums don't match :"
            echo "  script:     $this_checksum"
            echo "  calculated: $calculated_checksum"
            exit 1
        else
            echo "Checksum match !"
            exit 0
        fi
        ;;
        
    extract)
        if [ ! -d $EXTRACT_LOCATION ]
        then
            echo "$EXTRACT_LOCATION is not a directory."
            exit 1
        fi
        
        bootstrap_extract "$0" $(readlink -f $EXTRACT_LOCATION)
        ;;
        
    info)
        echo "Version: $BOOTSTRAP_SCRIPT_VERSION ($BOOTSTRAP_SCRIPT_BRANCH)"
        echo "Author:  $BOOTSTRAP_SCRIPT_AUTHOR"
        echo "Date:    $BOOTSTRAP_SCRIPT_DATE"
        echo "Compiled-in modules:"
        
        for m in $BOOTSTRAP_MODULES
        do
            echo "   * $m"
        done
        ;;
        
    version)
        echo "$BOOTSTRAP_SCRIPT_VERSION ($BOOTSTRAP_SCRIPT_BRANCH)"
        ;;
        
    help)
        echo "Usage: $0 [options]"
        echo "Options:"
        echo "  --help                 show this help"
        echo "  --version              display the current script version"
        echo "  --info                 print various information about this script"
        echo "  --root=ROOT            use ROOT as the target directory for bootstrapping "
        echo "                         (default: current dir.)"
        echo "  --extract-data=DIR     only extract the payload into the directory DIR."
        echo "  --install=MODULE       run the installation job for the module MODULE"
        echo ""
        ;;
        
    *)
        echo "I don't know how to do that."
        exit 1
        ;;
esac

# Cleaning up
